// src/app/components/strippenkaart/strippenkaart.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
    selector: 'app-strippenkaart',
    standalone: true,
    imports: [CommonModule],
    templateUrl: './strippenkaart.component.html',
})
export class StrippenkaartComponent {
    @Input() steps: any[] = [];

    // Configuration
    readonly stepHeight = 80;
    readonly lineWidth = 4;
    readonly stripLength = 30;
    readonly stripWidth = 3;
    readonly dotRadius = 8;
    readonly centerX = 150;

    get totalHeight(): number {
        return (this.steps?.length || 0) * this.stepHeight + 150;
    }

    getStrips(step: any): { left: number, right: number } {
        if (step.type === 'strip_entry') {
            return { left: step.left || 0, right: step.right || 0 };
        }

        let left = 0;
        let right = 0;
        const { type, action } = step;

        if (type === 'cross') {
            if (action === 'straight') { left = 1; right = 1; }
            else if (action === 'left') { right = 2; }
            else if (action === 'right') { left = 2; }
        }
        else if (type === 't_split') {
            if (action === 'left') { right = 1; }
            else if (action === 'right') { left = 1; }
        }
        else if (type === 't_split_left') {
            if (action === 'straight') { left = 1; }
            else if (action === 'left') { right = 1; }
        }
        else if (type === 't_split_right') {
            if (action === 'straight') { right = 1; }
            else if (action === 'right') { left = 1; }
        }
        else if (type === 'y_split') {
            if (action === 'slight_left' || action === 'left') { right = 1; }
            else if (action === 'slight_right' || action === 'right') { left = 1; }
        }

        return { left, right };
    }

    getFanLines(cx: number, cy: number, count: number, side: number): { x1: number, y1: number, x2: number, y2: number }[] {
        const lines: { x1: number, y1: number, x2: number, y2: number }[] = [];
        const angles: number[] = [];

        if (count === 1) angles.push(0);
        else if (count === 2) angles.push(25, -25);
        else if (count === 3) angles.push(35, 0, -35);
        else if (count === 4) angles.push(45, 15, -15, -45);

        angles.forEach(angle => {
            const rad = (angle * Math.PI) / 180;
            const x2 = cx + side * this.stripLength * Math.cos(rad);
            const y2 = cy - this.stripLength * Math.sin(rad);
            lines.push({ x1: cx, y1: cy, x2, y2 });
        });

        return lines;
    }

    getStepY(idx: number): number {
        return this.totalHeight - 50 - ((idx + 1) * this.stepHeight);
    }
}

<div class="w-full max-w-md mx-auto bg-white print:max-w-none print:w-auto" *ngIf="steps && steps.length > 0">
    <svg width="300" [attr.height]="totalHeight" [attr.viewBox]="'0 0 300 ' + totalHeight" class="mx-auto">
        <!-- Main Vertical Line -->
        <line [attr.x1]="centerX" [attr.y1]="totalHeight - 50" [attr.x2]="centerX" y2="50" stroke="black"
            [attr.stroke-width]="lineWidth" stroke-linecap="round" />

        <!-- Start Dot -->
        <circle [attr.cx]="centerX" [attr.cy]="totalHeight - 50" [attr.r]="dotRadius" fill="black" />

        <!-- End Bar -->
        <line [attr.x1]="centerX - 20" y1="50" [attr.x2]="centerX + 20" y2="50" stroke="black"
            [attr.stroke-width]="lineWidth * 1.5" />
        <text [attr.x]="centerX" y="30" text-anchor="middle" font-size="16" font-weight="bold">EIND</text>
        <text [attr.x]="centerX" [attr.y]="totalHeight - 20" text-anchor="middle" font-size="16"
            font-weight="bold">START</text>

        <!-- Steps -->
        <g *ngFor="let step of steps; let idx = index">
            <!-- Number -->
            <text [attr.x]="centerX + 50" [attr.y]="getStepY(idx) + 5" font-size="12" fill="gray">#{{ idx + 1 }}</text>

            <!-- Left Strips -->
            <ng-container *ngIf="getStrips(step).left > 0">
                <line *ngFor="let line of getFanLines(centerX, getStepY(idx), getStrips(step).left, -1)"
                    [attr.x1]="line.x1" [attr.y1]="line.y1" [attr.x2]="line.x2" [attr.y2]="line.y2" stroke="black"
                    [attr.stroke-width]="stripWidth" stroke-linecap="round" />
            </ng-container>

            <!-- Right Strips -->
            <ng-container *ngIf="getStrips(step).right > 0">
                <line *ngFor="let line of getFanLines(centerX, getStepY(idx), getStrips(step).right, 1)"
                    [attr.x1]="line.x1" [attr.y1]="line.y1" [attr.x2]="line.x2" [attr.y2]="line.y2" stroke="black"
                    [attr.stroke-width]="stripWidth" stroke-linecap="round" />
            </ng-container>
        </g>
    </svg>
</div>

// legacy_backup/src/components/Strippenkaart.jsx
import React from 'react';

const Strippenkaart = ({ steps }) => {
    if (!steps || steps.length === 0) return null;

    // Configuration
    const stepHeight = 80;
    const lineWidth = 4;
    const stripLength = 30;
    const stripWidth = 3;
    const dotRadius = 8;
    // Increased padding from 100 to 150 to prevent overlap with End Bar
    const totalHeight = steps.length * stepHeight + 150;
    const centerX = 150; // Center of the SVG

    // Helper to calculate strips for a step
    const getStrips = (step) => {
        // Direct input support
        if (step.type === 'strip_entry') {
            return { left: step.left || 0, right: step.right || 0 };
        }

        // Legacy support for intersection types
        let left = 0;
        let right = 0;
        const { type, action } = step;

        if (type === 'cross') {
            if (action === 'straight') { left = 1; right = 1; }
            else if (action === 'left') { right = 2; }
            else if (action === 'right') { left = 2; }
        }
        else if (type === 't_split') {
            if (action === 'left') { right = 1; }
            else if (action === 'right') { left = 1; }
        }
        else if (type === 't_split_left') {
            if (action === 'straight') { left = 1; }
            else if (action === 'left') { right = 1; }
        }
        else if (type === 't_split_right') {
            if (action === 'straight') { right = 1; }
            else if (action === 'right') { left = 1; }
        }
        else if (type === 'y_split') {
            if (action === 'slight_left' || action === 'left') { right = 1; }
            else if (action === 'slight_right' || action === 'right') { left = 1; }
        }

        return { left, right };
    };

    // Helper to generate lines for a fan of strips
    const getFanLines = (cx, cy, count, side) => {
        // side: -1 for left, 1 for right
        const lines = [];
        const angles = [];

        if (count === 1) angles.push(0);
        else if (count === 2) angles.push(25, -25); // V-shape
        else if (count === 3) angles.push(35, 0, -35); // Fan
        else if (count === 4) angles.push(45, 15, -15, -45); // Star burst

        angles.forEach(angle => {
            const rad = (angle * Math.PI) / 180;
            // y grows down, so -sin for up
            const x2 = cx + side * stripLength * Math.cos(rad);
            const y2 = cy - stripLength * Math.sin(rad);
            lines.push({ x1: cx, y1: cy, x2, y2 });
        });

        return lines;
    };

    return (
        <div className="w-full max-w-md mx-auto bg-white print:max-w-none print:w-auto">
            <svg
                width="300"
                height={totalHeight}
                viewBox={`0 0 300 ${totalHeight}`}
                className="mx-auto"
            >
                {/* Main Vertical Line */}
                <line
                    x1={centerX}
                    y1={totalHeight - 50}
                    x2={centerX}
                    y2={50}
                    stroke="black"
                    strokeWidth={lineWidth}
                    strokeLinecap="round"
                />

                {/* Start Dot */}
                <circle cx={centerX} cy={totalHeight - 50} r={dotRadius} fill="black" />

                {/* End Bar */}
                <line
                    x1={centerX - 20}
                    y1={50}
                    x2={centerX + 20}
                    y2={50}
                    stroke="black"
                    strokeWidth={lineWidth * 1.5}
                />
                <text x={centerX} y={30} textAnchor="middle" fontSize="16" fontWeight="bold">EIND</text>
                <text x={centerX} y={totalHeight - 20} textAnchor="middle" fontSize="16" fontWeight="bold">START</text>

                {/* Steps */}
                {steps.map((step, idx) => {
                    // Draw from bottom to top
                    const y = totalHeight - 50 - ((idx + 1) * stepHeight);
                    const { left, right } = getStrips(step);

                    return (
                        <g key={step.id || idx}>
                            {/* Number */}
                            <text x={centerX + 50} y={y + 5} fontSize="12" fill="gray">#{idx + 1}</text>

                            {/* Left Strips */}
                            {left > 0 && getFanLines(centerX, y, left, -1).map((line, i) => (
                                <line
                                    key={`l-${i}`}
                                    x1={line.x1} y1={line.y1}
                                    x2={line.x2} y2={line.y2}
                                    stroke="black"
                                    strokeWidth={stripWidth}
                                    strokeLinecap="round"
                                />
                            ))}

                            {/* Right Strips */}
                            {right > 0 && getFanLines(centerX, y, right, 1).map((line, i) => (
                                <line
                                    key={`r-${i}`}
                                    x1={line.x1} y1={line.y1}
                                    x2={line.x2} y2={line.y2}
                                    stroke="black"
                                    strokeWidth={stripWidth}
                                    strokeLinecap="round"
                                />
                            ))}
                        </g>
                    );
                })}
            </svg>
        </div>
    );
};

export default Strippenkaart;
