// src/app/components/tulip-diagram/tulip-diagram.component.ts
import { Component, Input, OnChanges, SimpleChanges } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
    selector: 'app-tulip-diagram',
    standalone: true,
    imports: [CommonModule],
    templateUrl: './tulip-diagram.component.html',
})
export class TulipDiagramComponent implements OnChanges {
    @Input() type: string = 'cross';
    @Input() action: string = 'straight';
    @Input() size: number = 100;
    @Input() showArrow: boolean = true;

    roads: string[] = [];
    arrowPath: string = '';
    arrowHeadPoints: string = '';

    // Constants
    readonly cx = 50;
    readonly cy = 50;
    readonly roadWidth = 20;
    readonly roadColor = "white";
    readonly roadBorder = "black";
    readonly arrowColor = "black";
    readonly startX = 50;
    readonly startY = 85;
    readonly elbowX = 50;
    readonly elbowY = 50;

    endX = 0;
    endY = 0;

    ngOnChanges(changes: SimpleChanges) {
        this.calculateRoads();
        this.calculateArrow();
    }

    private createRoadPath(angleDeg: number): string {
        const rad = (angleDeg * Math.PI) / 180;
        const length = 60;
        const x = this.cx + length * Math.cos(rad);
        const y = this.cy + length * Math.sin(rad);

        const perp = rad + Math.PI / 2;
        const dx = (this.roadWidth / 2) * Math.cos(perp);
        const dy = (this.roadWidth / 2) * Math.sin(perp);

        return `M ${this.cx - dx} ${this.cy - dy} L ${x - dx} ${y - dy} L ${x + dx} ${y + dy} L ${this.cx + dx} ${this.cy + dy} Z`;
    }

    private calculateRoads() {
        this.roads = [this.createRoadPath(90)]; // Incoming from bottom

        switch (this.type) {
            case 'cross':
                this.roads.push(this.createRoadPath(270)); // Up
                this.roads.push(this.createRoadPath(180)); // Left
                this.roads.push(this.createRoadPath(0));   // Right
                break;
            case 't_split':
                this.roads.push(this.createRoadPath(180)); // Left
                this.roads.push(this.createRoadPath(0));   // Right
                break;
            case 't_split_left':
                this.roads.push(this.createRoadPath(270)); // Up
                this.roads.push(this.createRoadPath(180)); // Left
                break;
            case 't_split_right':
                this.roads.push(this.createRoadPath(270)); // Up
                this.roads.push(this.createRoadPath(0));   // Right
                break;
            case 'y_split':
                this.roads.push(this.createRoadPath(225)); // Up-Left
                this.roads.push(this.createRoadPath(315)); // Up-Right
                break;
            case 'straight':
                this.roads.push(this.createRoadPath(270)); // Up
                break;
            default:
                this.roads.push(this.createRoadPath(270));
                this.roads.push(this.createRoadPath(180));
                this.roads.push(this.createRoadPath(0));
        }
    }

    private calculateArrow() {
        let rad = -Math.PI / 2; // Default Up

        switch (this.action) {
            case 'straight': rad = -Math.PI / 2; break;
            case 'left': rad = Math.PI; break;
            case 'right': rad = 0; break;
            case 'slight_left': rad = -Math.PI * 0.75; break;
            case 'slight_right': rad = -Math.PI * 0.25; break;
            case 'sharp_left': rad = Math.PI * 0.75; break;
            case 'sharp_right': rad = Math.PI * 0.25; break;
            case 'uturn': rad = Math.PI / 2; break;
        }

        const arrowLen = 35;
        this.endX = this.elbowX + arrowLen * Math.cos(rad);
        this.endY = this.elbowY + arrowLen * Math.sin(rad);

        this.arrowPath = `M ${this.startX} ${this.startY} L ${this.elbowX} ${this.elbowY} L ${this.endX} ${this.endY}`;

        // Arrowhead
        const arrowHeadLen = 8;
        const arrowAngle1 = rad + Math.PI * 0.85;
        const arrowAngle2 = rad - Math.PI * 0.85;

        const ahX1 = this.endX + arrowHeadLen * Math.cos(arrowAngle1);
        const ahY1 = this.endY + arrowHeadLen * Math.sin(arrowAngle1);
        const ahX2 = this.endX + arrowHeadLen * Math.cos(arrowAngle2);
        const ahY2 = this.endY + arrowHeadLen * Math.sin(arrowAngle2);

        this.arrowHeadPoints = `${this.endX},${this.endY} ${ahX1},${ahY1} ${ahX2},${ahY2}`;
    }
}

<svg [attr.width]="size" [attr.height]="size" viewBox="0 0 100 100" class="bg-white">
    <g [attr.stroke]="roadBorder" stroke-width="2" [attr.fill]="roadColor">
        <path *ngFor="let d of roads" [attr.d]="d" />
        <circle [attr.cx]="cx" [attr.cy]="cy" [attr.r]="roadWidth / 2" stroke="none" [attr.fill]="roadColor" />
    </g>

    <g *ngIf="showArrow" fill="none" [attr.stroke]="arrowColor" stroke-width="2" stroke-linecap="round"
        stroke-linejoin="round">
        <circle [attr.cx]="startX" [attr.cy]="startY" r="3" [attr.fill]="arrowColor" stroke="none" />
        <path [attr.d]="arrowPath" />
        <polygon [attr.points]="arrowHeadPoints" [attr.fill]="arrowColor" stroke="none" />
    </g>
</svg>

// legacy_backup/src/components/TulipDiagram.jsx
import React from 'react';

const TulipDiagram = ({ type = 'cross', action = 'straight', size = 100, showArrow = true }) => {
    // Center of the SVG
    const cx = 50;
    const cy = 50;

    // Configuration
    const roadWidth = 20;
    const roadColor = "white";
    const roadBorder = "black";
    const arrowColor = "black";

    // Helper to create road path based on angle (0 = Right, 90 = Down, 180 = Left, 270 = Up)
    const createRoadPath = (angleDeg) => {
        const rad = (angleDeg * Math.PI) / 180;
        const length = 60;
        const x = cx + length * Math.cos(rad);
        const y = cy + length * Math.sin(rad);

        const perp = rad + Math.PI / 2;
        const dx = (roadWidth / 2) * Math.cos(perp);
        const dy = (roadWidth / 2) * Math.sin(perp);

        return `M ${cx - dx} ${cy - dy} L ${x - dx} ${y - dy} L ${x + dx} ${y + dy} L ${cx + dx} ${cy + dy} Z`;
    };

    // Define Roads based on Type
    // Incoming is always from Bottom (90 degrees)
    const roads = [createRoadPath(90)];

    switch (type) {
        case 'cross': // 4-sprong
            roads.push(createRoadPath(270)); // Up
            roads.push(createRoadPath(180)); // Left
            roads.push(createRoadPath(0));   // Right
            break;
        case 't_split': // T-splitsing (Top bar)
            roads.push(createRoadPath(180)); // Left
            roads.push(createRoadPath(0));   // Right
            break;
        case 't_split_left': // Side road left
            roads.push(createRoadPath(270)); // Up
            roads.push(createRoadPath(180)); // Left
            break;
        case 't_split_right': // Side road right
            roads.push(createRoadPath(270)); // Up
            roads.push(createRoadPath(0));   // Right
            break;
        case 'y_split': // Y-splitsing
            roads.push(createRoadPath(225)); // Up-Left
            roads.push(createRoadPath(315)); // Up-Right
            break;
        case 'straight': // Just straight road (for side road logic maybe?)
            roads.push(createRoadPath(270)); // Up
            break;
        default:
            roads.push(createRoadPath(270)); // Default straight
            roads.push(createRoadPath(180));
            roads.push(createRoadPath(0));
    }

    // Define Arrow Path based on Action
    // Start dot
    const startX = 50;
    const startY = 85;
    const elbowX = 50;
    const elbowY = 50;

    let endX, endY;
    let rad = -Math.PI / 2; // Default Up

    switch (action) {
        case 'straight':
            rad = -Math.PI / 2; // Up
            break;
        case 'left':
            rad = Math.PI; // Left
            break;
        case 'right':
            rad = 0; // Right
            break;
        case 'slight_left':
            rad = -Math.PI * 0.75; // Up-Left
            break;
        case 'slight_right':
            rad = -Math.PI * 0.25; // Up-Right
            break;
        case 'sharp_left':
            rad = Math.PI * 0.75; // Down-Left
            break;
        case 'sharp_right':
            rad = Math.PI * 0.25; // Down-Right
            break;
        case 'uturn':
            rad = Math.PI / 2; // Down
            break;
    }

    const arrowLen = 35;
    endX = elbowX + arrowLen * Math.cos(rad);
    endY = elbowY + arrowLen * Math.sin(rad);

    // Arrowhead
    const arrowHeadLen = 8;
    const arrowAngle1 = rad + Math.PI * 0.85;
    const arrowAngle2 = rad - Math.PI * 0.85;

    const ahX1 = endX + arrowHeadLen * Math.cos(arrowAngle1);
    const ahY1 = endY + arrowHeadLen * Math.sin(arrowAngle1);
    const ahX2 = endX + arrowHeadLen * Math.cos(arrowAngle2);
    const ahY2 = endY + arrowHeadLen * Math.sin(arrowAngle2);

    return (
        <svg
            width={size}
            height={size}
            viewBox="0 0 100 100"
            className="bg-white"
        >
            <g stroke={roadBorder} strokeWidth="2" fill={roadColor}>
                {roads.map((d, i) => <path key={i} d={d} />)}
                {/* Fix: Reduced radius to exactly roadWidth/2 to prevent bulge artifacts */}
                <circle cx={cx} cy={cy} r={roadWidth / 2} stroke="none" fill={roadColor} />
            </g>

            {showArrow && (
                <g fill="none" stroke={arrowColor} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <circle cx={startX} cy={startY} r="3" fill={arrowColor} stroke="none" />
                    <path d={`M ${startX} ${startY} L ${elbowX} ${elbowY} L ${endX} ${endY}`} />
                    <polygon
                        points={`${endX},${endY} ${ahX1},${ahY1} ${ahX2},${ahY2}`}
                        fill={arrowColor}
                        stroke="none"
                    />
                </g>
            )}
        </svg>
    );
};

export default TulipDiagram;
