// src/app/components/interactive-tulip/interactive-tulip.component.ts
import { Component, Input, Output, EventEmitter, OnChanges, SimpleChanges } from '@angular/core';
import { CommonModule } from '@angular/common';
import { TulipDiagramComponent } from '../tulip-diagram/tulip-diagram.component';

interface Zone {
    action: string;
    path: string;
}

@Component({
    selector: 'app-interactive-tulip',
    standalone: true,
    imports: [CommonModule, TulipDiagramComponent],
    templateUrl: './interactive-tulip.component.html',
})
export class InteractiveTulipComponent implements OnChanges {
    @Input() type: string = 'cross';
    @Input() size: number = 300;
    @Output() actionSelect = new EventEmitter<string>();

    hoverAction: string | null = null;
    zones: Zone[] = [];

    // Common zones
    private readonly topZone: Zone = { action: 'straight', path: 'M 30 0 L 70 0 L 70 40 L 30 40 Z' };
    private readonly leftZone: Zone = { action: 'left', path: 'M 0 30 L 40 30 L 40 70 L 0 70 Z' };
    private readonly rightZone: Zone = { action: 'right', path: 'M 60 30 L 100 30 L 100 70 L 60 70 Z' };
    private readonly topLeftZone: Zone = { action: 'slight_left', path: 'M 0 0 L 50 0 L 50 50 L 0 50 Z' };
    private readonly topRightZone: Zone = { action: 'slight_right', path: 'M 50 0 L 100 0 L 100 50 L 50 50 Z' };

    ngOnChanges(changes: SimpleChanges) {
        if (changes['type']) {
            this.calculateZones();
        }
    }

    private calculateZones() {
        this.zones = [];
        switch (this.type) {
            case 'cross':
                this.zones.push(this.topZone, this.leftZone, this.rightZone);
                break;
            case 't_split':
                this.zones.push(this.leftZone, this.rightZone);
                break;
            case 't_split_left':
                this.zones.push(this.topZone, this.leftZone);
                break;
            case 't_split_right':
                this.zones.push(this.topZone, this.rightZone);
                break;
            case 'y_split':
                this.zones.push(this.topLeftZone, this.topRightZone);
                break;
            case 'straight':
                this.zones.push(this.topZone);
                break;
            default:
                this.zones.push(this.topZone, this.leftZone, this.rightZone);
        }
    }

    setHoverAction(action: string | null) {
        this.hoverAction = action;
    }

    selectAction(action: string) {
        this.actionSelect.emit(action);
    }
}

<div class="relative inline-block cursor-pointer">
    <!-- Base Diagram (No Arrow) -->
    <app-tulip-diagram [type]="type" [showArrow]="false" [size]="size"></app-tulip-diagram>

    <!-- Ghost Arrow Layer -->
    <div *ngIf="hoverAction" class="absolute inset-0 pointer-events-none opacity-50">
        <app-tulip-diagram [type]="type" [action]="hoverAction" [showArrow]="true" [size]="size"></app-tulip-diagram>
    </div>

    <!-- Interaction Layer -->
    <svg class="absolute inset-0 w-full h-full" viewBox="0 0 100 100" preserveAspectRatio="none">
        <path *ngFor="let zone of zones" [attr.d]="zone.path" fill="transparent" stroke="none"
            class="hover:fill-green-500/20 transition-colors" (mouseenter)="setHoverAction(zone.action)"
            (mouseleave)="setHoverAction(null)" (click)="selectAction(zone.action)" />
    </svg>

    <div class="absolute bottom-2 left-0 right-0 text-center text-sm text-gray-500 pointer-events-none">
        Klik op de weg die je in wilt slaan
    </div>
</div>

// src/components/InteractiveTulip.jsx
import React, { useState } from 'react';
import TulipDiagram from './TulipDiagram';

const InteractiveTulip = ({ type, onActionSelect, size = 300 }) => {
    const [hoverAction, setHoverAction] = useState(null);

    // Define click zones based on type
    // Each zone has a path (for hit detection) and an action
    const zones = [];

    // Common zones
    const topZone = { action: 'straight', path: 'M 30 0 L 70 0 L 70 40 L 30 40 Z' };
    const leftZone = { action: 'left', path: 'M 0 30 L 40 30 L 40 70 L 0 70 Z' };
    const rightZone = { action: 'right', path: 'M 60 30 L 100 30 L 100 70 L 60 70 Z' };
    const topLeftZone = { action: 'slight_left', path: 'M 0 0 L 50 0 L 50 50 L 0 50 Z' };
    const topRightZone = { action: 'slight_right', path: 'M 50 0 L 100 0 L 100 50 L 50 50 Z' };

    switch (type) {
        case 'cross':
            zones.push(topZone, leftZone, rightZone);
            break;
        case 't_split':
            zones.push(leftZone, rightZone);
            break;
        case 't_split_left':
            zones.push(topZone, leftZone);
            break;
        case 't_split_right':
            zones.push(topZone, rightZone);
            break;
        case 'y_split':
            zones.push(topLeftZone, topRightZone);
            break;
        case 'straight':
            zones.push(topZone);
            break;
        default:
            zones.push(topZone, leftZone, rightZone);
    }

    return (
        <div className="relative inline-block cursor-pointer">
            {/* Base Diagram (No Arrow) */}
            <TulipDiagram type={type} showArrow={false} size={size} />

            {/* Ghost Arrow Layer */}
            {hoverAction && (
                <div className="absolute inset-0 pointer-events-none opacity-50">
                    <TulipDiagram type={type} action={hoverAction} showArrow={true} size={size} />
                </div>
            )}

            {/* Interaction Layer */}
            <svg
                className="absolute inset-0 w-full h-full"
                viewBox="0 0 100 100"
                preserveAspectRatio="none"
            >
                {zones.map((zone, i) => (
                    <path
                        key={i}
                        d={zone.path}
                        fill="transparent"
                        stroke="none"
                        className="hover:fill-green-500/20 transition-colors"
                        onMouseEnter={() => setHoverAction(zone.action)}
                        onMouseLeave={() => setHoverAction(null)}
                        onClick={() => onActionSelect(zone.action)}
                    />
                ))}
            </svg>

            <div className="absolute bottom-2 left-0 right-0 text-center text-sm text-gray-500 pointer-events-none">
                Klik op de weg die je in wilt slaan
            </div>
        </div>
    );
};

export default InteractiveTulip;
