// src/app/app.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { LucideAngularModule, Map, Printer, Home, LogIn, User } from 'lucide-angular';
import { AuthService } from './services/auth.service';

@Component({
    selector: 'app-root',
    standalone: true,
    imports: [
        CommonModule,
        RouterModule,
        LucideAngularModule
    ],
    templateUrl: './app.component.html',
})
export class AppComponent {
    // Icons
    readonly Map = Map;
    readonly Printer = Printer;
    readonly Home = Home;
    readonly LogIn = LogIn;
    readonly User = User;

    constructor(public authService: AuthService) { }

    handlePrint() {
        window.print();
    }
}

<div class="min-h-screen bg-gray-100 font-sans text-gray-900">
    <!-- Navigation Bar - Hidden in Print -->
    <nav class="bg-white shadow-sm border-b border-gray-200 print:hidden sticky top-0 z-50">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div class="flex justify-between h-16">
                <div class="flex items-center gap-2 cursor-pointer" (click)="setView('landing')">
                    <div class="bg-blue-600 p-2 rounded-lg">
                        <lucide-icon [img]="Map" class="w-6 h-6 text-white"></lucide-icon>
                    </div>
                    <span
                        class="text-xl font-bold bg-gradient-to-r from-blue-700 to-blue-500 bg-clip-text text-transparent">
                        RouteMaker
                    </span>
                </div>

                <div class="flex items-center gap-4">
                    <div *ngIf="view === 'builder'" class="flex items-center gap-4">
                        <button (click)="setView('landing')"
                            class="flex items-center gap-2 text-gray-500 hover:text-blue-600 transition px-3 py-2 rounded-md hover:bg-blue-50">
                            <lucide-icon [img]="Home" class="w-5 h-5"></lucide-icon>
                            <span class="hidden sm:inline">Home</span>
                        </button>
                        <button (click)="handlePrint()"
                            class="flex items-center gap-2 bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition shadow-md hover:shadow-lg">
                            <lucide-icon [img]="Printer" class="w-5 h-5"></lucide-icon>
                            <span>Afdrukken</span>
                        </button>
                    </div>

                    <!-- Auth Button -->
                    <button *ngIf="!authService.isLoggedIn()" (click)="setView('login')"
                        class="flex items-center gap-2 text-gray-600 hover:text-blue-600 transition px-3 py-2 rounded-md hover:bg-blue-50">
                        <lucide-icon [img]="LogIn" class="w-5 h-5"></lucide-icon>
                        <span class="hidden sm:inline">Inloggen</span>
                    </button>

                    <div *ngIf="authService.isLoggedIn()" class="flex items-center gap-4">
                        <button *ngIf="authService.isAdmin()" (click)="setView('admin')"
                            class="flex items-center gap-2 text-gray-600 hover:text-blue-600 transition px-3 py-2 rounded-md hover:bg-blue-50">
                            <lucide-icon [img]="User" class="w-5 h-5"></lucide-icon>
                            <span class="hidden sm:inline">Admin</span>
                        </button>
                        <span class="text-sm font-medium text-gray-700">
                            {{ (authService.currentUser$ | async)?.username }}
                        </span>
                        <button (click)="authService.logout()"
                            class="text-sm text-red-600 hover:text-red-700 font-medium">
                            Uitloggen
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </nav>

    <!-- Main Content -->
    <main class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 print:p-0 print:max-w-none">

        <!-- Landing Page -->
        <app-landing-page *ngIf="view === 'landing'" (routeSelect)="handleStart($event)"></app-landing-page>

        <!-- Login View -->
        <app-login *ngIf="view === 'login'" (loginSuccess)="handleLoginSuccess()"></app-login>

        <!-- Admin Dashboard -->
        <app-admin-dashboard *ngIf="view === 'admin'"></app-admin-dashboard>

        <!-- Builder View -->
        <div *ngIf="view === 'builder'" class="space-y-8">
            <!-- Editor Interface - Hidden in Print -->
            <div class="print:hidden">
                <app-route-builder [(steps)]="steps" [routeType]="routeType" [(heliScale)]="heliScale"
                    [(ogenTheme)]="ogenTheme"></app-route-builder>
            </div>

            <!-- Print View -->
            <div class="hidden print:block">
                <!-- Header - Conditional for Helicopter -->
                <div *ngIf="routeType !== 'helicopter'" class="mb-8 text-center border-b-2 border-black pb-4">
                    <h1 class="text-4xl font-bold uppercase tracking-wider">Routeboek</h1>
                    <p class="text-gray-500 mt-2">Gegenereerd met RouteMaker</p>
                </div>

                <!-- Content based on Route Type -->
                <app-route-table *ngIf="routeType === 'tulip'" [steps]="steps"></app-route-table>

                <app-strippenkaart *ngIf="routeType === 'strip'" [steps]="steps"></app-strippenkaart>

                <app-helicopter-route *ngIf="routeType === 'helicopter'" [steps]="steps"
                    [scale]="heliScale"></app-helicopter-route>

                <app-ogen-route *ngIf="routeType === 'ogen'" [steps]="steps" [theme]="ogenTheme"></app-ogen-route>
            </div>
        </div>
    </main>
</div>

// src/App.jsx
import React, { useState } from 'react';
import { Map, Printer, Home } from 'lucide-react';
import RouteBuilder from './components/RouteBuilder';
import RouteTable from './components/RouteTable';
import LandingPage from './components/LandingPage';
import Strippenkaart from './components/Strippenkaart';
import HelicopterRoute from './components/HelicopterRoute';

function App() {
  const [view, setView] = useState('landing'); // 'landing' or 'builder'
  const [routeType, setRouteType] = useState('tulip'); // 'tulip', 'strip', 'helicopter'
  const [steps, setSteps] = useState([]);
  const [heliScale, setHeliScale] = useState(100); // Default scale for helicopter

  const handleStart = (type) => {
    setRouteType(type);
    setView('builder');
    setSteps([]); // Reset steps when starting new
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="min-h-screen bg-gray-100 font-sans text-gray-900">
      {/* Navigation Bar - Hidden in Print */}
      <nav className="bg-white shadow-sm border-b border-gray-200 print:hidden sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between h-16">
            <div className="flex items-center gap-2 cursor-pointer" onClick={() => setView('landing')}>
              <div className="bg-blue-600 p-2 rounded-lg">
                <Map className="w-6 h-6 text-white" />
              </div>
              <span className="text-xl font-bold bg-gradient-to-r from-blue-700 to-blue-500 bg-clip-text text-transparent">
                RouteMaker
              </span>
            </div>

            {view === 'builder' && (
              <div className="flex items-center gap-4">
                <button
                  onClick={() => setView('landing')}
                  className="flex items-center gap-2 text-gray-500 hover:text-blue-600 transition px-3 py-2 rounded-md hover:bg-blue-50"
                >
                  <Home className="w-5 h-5" />
                  <span className="hidden sm:inline">Home</span>
                </button>
                <button
                  onClick={handlePrint}
                  className="flex items-center gap-2 bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition shadow-md hover:shadow-lg"
                >
                  <Printer className="w-5 h-5" />
                  <span>Afdrukken</span>
                </button>
              </div>
            )}
          </div>
        </div>
      </nav>

      {/* Main Content */}
      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 print:p-0 print:max-w-none">

        {/* Landing Page */}
        {view === 'landing' && (
          <LandingPage onStart={handleStart} />
        )}

        {/* Builder View */}
        {view === 'builder' && (
          <div className="space-y-8">
            {/* Editor Interface - Hidden in Print */}
            <div className="print:hidden">
              <RouteBuilder
                steps={steps}
                setSteps={setSteps}
                routeType={routeType}
                heliScale={heliScale}
                setHeliScale={setHeliScale}
              />
            </div>

            {/* Print View */}
            <div className="hidden print:block">
              {/* Header - Conditional for Helicopter */}
              {routeType !== 'helicopter' && (
                <div className="mb-8 text-center border-b-2 border-black pb-4">
                  <h1 className="text-4xl font-bold uppercase tracking-wider">Routeboek</h1>
                  <p className="text-gray-500 mt-2">Gegenereerd met RouteMaker</p>
                </div>
              )}

              {/* Content based on Route Type */}
              {routeType === 'tulip' && (
                <RouteTable steps={steps} />
              )}

              {routeType === 'strip' && (
                <Strippenkaart steps={steps} />
              )}

              {routeType === 'helicopter' && (
                <HelicopterRoute steps={steps} scale={heliScale} />
              )}
            </div>
          </div>
        )}
      </main>
    </div>
  );
}

export default App;
